-- RoyalsMarket initial schema.
-- Portable across H2 (dev) and PostgreSQL (prod); Flyway owns the schema (ddl-auto=none).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)  NOT NULL,
    email         VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    ign           VARCHAR(30),
    discord_tag   VARCHAR(50),
    role          VARCHAR(10)  NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);

CREATE TABLE listings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id     BIGINT       NOT NULL,
    title         VARCHAR(120) NOT NULL,
    category      VARCHAR(20)  NOT NULL,
    description   VARCHAR(4000),
    image_url     VARCHAR(500),
    quantity      INTEGER      NOT NULL,
    type          VARCHAR(10)  NOT NULL,
    status        VARCHAR(10)  NOT NULL,
    price         BIGINT       NOT NULL,
    buy_now_price BIGINT,
    allow_offers  BOOLEAN      NOT NULL,
    ends_at       TIMESTAMP,
    winner_id     BIGINT,
    final_price   BIGINT,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_listings_seller FOREIGN KEY (seller_id) REFERENCES users (id),
    CONSTRAINT fk_listings_winner FOREIGN KEY (winner_id) REFERENCES users (id)
);

CREATE INDEX idx_listings_status     ON listings (status);
CREATE INDEX idx_listings_type       ON listings (type);
CREATE INDEX idx_listings_category   ON listings (category);
CREATE INDEX idx_listings_created_at ON listings (created_at);
CREATE INDEX idx_listings_seller     ON listings (seller_id);

CREATE TABLE bids (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT    NOT NULL,
    bidder_id  BIGINT    NOT NULL,
    amount     BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bids_listing FOREIGN KEY (listing_id) REFERENCES listings (id),
    CONSTRAINT fk_bids_bidder  FOREIGN KEY (bidder_id)  REFERENCES users (id)
);

CREATE INDEX idx_bids_listing ON bids (listing_id);

CREATE TABLE offers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT      NOT NULL,
    buyer_id   BIGINT      NOT NULL,
    amount     BIGINT      NOT NULL,
    message    VARCHAR(500),
    status     VARCHAR(10) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT fk_offers_listing FOREIGN KEY (listing_id) REFERENCES listings (id),
    CONSTRAINT fk_offers_buyer   FOREIGN KEY (buyer_id)   REFERENCES users (id)
);

CREATE INDEX idx_offers_listing ON offers (listing_id);

CREATE TABLE conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id      BIGINT,
    participant_a   BIGINT    NOT NULL,
    participant_b   BIGINT    NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    last_message_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_conversations_listing FOREIGN KEY (listing_id)    REFERENCES listings (id),
    CONSTRAINT fk_conversations_a       FOREIGN KEY (participant_a) REFERENCES users (id),
    CONSTRAINT fk_conversations_b       FOREIGN KEY (participant_b) REFERENCES users (id)
);

CREATE INDEX idx_conversations_a ON conversations (participant_a);
CREATE INDEX idx_conversations_b ON conversations (participant_b);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT       NOT NULL,
    sender_id       BIGINT       NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    sent_at         TIMESTAMP    NOT NULL,
    read_at         TIMESTAMP,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_messages_sender       FOREIGN KEY (sender_id)       REFERENCES users (id)
);

CREATE INDEX idx_messages_conversation ON messages (conversation_id);
