-- Item catalog: sellers pick a known item instead of typing a free-text title.

CREATE TABLE catalog_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    category   VARCHAR(20)  NOT NULL,
    equip_type VARCHAR(20),
    item_class VARCHAR(20),
    icon_url   VARCHAR(500)
);
CREATE INDEX idx_catalog_item_category ON catalog_item (category);

-- Clear existing (demo) listing data and its dependents so listings can be restructured.
-- Order matters for foreign keys.
DELETE FROM messages;
DELETE FROM conversations;
DELETE FROM offers;
DELETE FROM bids;
DELETE FROM listings;

-- Restructure listings: drop free-text title/category, add catalog item + upgrade slots.
ALTER TABLE listings DROP COLUMN title;
DROP INDEX IF EXISTS idx_listings_category;
ALTER TABLE listings DROP COLUMN category;
ALTER TABLE listings ADD COLUMN catalog_item_id BIGINT NOT NULL;
ALTER TABLE listings ADD COLUMN slots_remaining INTEGER;
ALTER TABLE listings ADD CONSTRAINT fk_listings_item FOREIGN KEY (catalog_item_id) REFERENCES catalog_item (id);
CREATE INDEX idx_listings_item ON listings (catalog_item_id);

-- Structured per-listing stat values (gear only).
CREATE TABLE listing_stat (
    listing_id BIGINT      NOT NULL,
    stat_type  VARCHAR(10) NOT NULL,
    stat_value INTEGER     NOT NULL,
    PRIMARY KEY (listing_id, stat_type),
    CONSTRAINT fk_listing_stat_listing FOREIGN KEY (listing_id) REFERENCES listings (id)
);
